<a href="https://colab.research.google.com/github/dannabarrera292002PROGRAMACION/PROGRAMACION-/blob/main/Crypto_Fund.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install yfinance pandas plotly streamlit

import yfinance as yf
import pandas as pd
import plotly.express as px
import streamlit as st

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Collecting streamlit
  Downloading streamlit-1.57.0-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.9.6)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.5)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.1)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.3)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.47)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.46.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.26)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.20.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.13)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.4.22)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (13.9.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.7->yfinance) (0.1.2)
Downloading streamlit-1.57.0-py3-none-any.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 49.5 MB/s eta 0:00:00
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 76.2 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.2 streamlit-1.57.0

In [ ]:
import yfinance as yf

# Descargar datos de cada criptomoneda
btc = yf.download("BTC-USD", start="2026-04-01", end="2026-04-30", interval="1d")
eth = yf.download("ETH-USD", start="2026-04-01", end="2026-04-30", interval="1d")
sol = yf.download("SOL-USD", start="2026-04-01", end="2026-04-30", interval="1d")
ada = yf.download("ADA-USD", start="2026-04-01", end="2026-04-30", interval="1d")
ltc = yf.download("LTC-USD", start="2026-04-01", end="2026-04-30", interval="1d")

/tmp/ipykernel_2278/4141816512.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  btc = yf.download("BTC-USD", start="2026-04-01", end="2026-04-30", interval="1d")
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_2278/4141816512.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  eth = yf.download("ETH-USD", start="2026-04-01", end="2026-04-30", interval="1d")
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_2278/4141816512.py:6: FutureWarning: YF.download() has changed argument auto_adjust default to True
  sol = yf.download("SOL-USD", start="2026-04-01", end="2026-04-30", interval="1d")
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_2278/4141816512.py:7: FutureWarning: YF.download() has changed argument auto_adjust default to True
  ada = yf.download("ADA-USD", start="2026-04-01", end="2026-04-30", interval="1d")
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_2278/4141816512.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  ltc = yf.download("LTC-USD", start="2026-04-01", end="2026-04-30", interval="1d")
[*********************100%***********************]  1 of 1 completed

In [ ]:
btc.head()

Price,Close,High,Low,Open,Volume,retorno
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD,
Date,,,,,,
2026-04-01,68078.554688,69230.359375,67555.359375,68232.890625,36465393617,NaN
2026-04-02,66888.570312,68633.148438,65725.257812,68077.898438,39323384518,NaN
2026-04-03,66931.101562,67296.234375,66281.539062,66889.015625,22815543346,NaN
2026-04-04,67290.515625,67515.015625,66769.640625,66938.648438,15878814963,NaN
2026-04-05,68981.898438,69087.656250,66610.632812,67291.195312,22972648674,NaN

In [ ]:
eth.head()

In [ ]:
sol.head()

In [ ]:
ada.head()

In [ ]:
ltc.head()

In [ ]:
# btc['Close'] tiene los precios de cierre
btc['retorno'] = btc['Close'].pct_change()
eth['retorno'] = eth['Close'].pct_change()
sol['retorno'] = sol['Close'].pct_change()
ada['retorno'] = ada['Close'].pct_change()
ltc['retorno'] = ltc['Close'].pct_change()

In [ ]:
# Mostrar solo 'close' y 'retorno' para BTC
btc[['Close', 'retorno']].head()

Price              Close   retorno
Ticker           BTC-USD
Date
2026-04-01  68078.554688       NaN
2026-04-02  66888.570312 -0.017480
2026-04-03  66931.101562  0.000636
2026-04-04  67290.515625  0.005370
2026-04-05  68981.898438  0.025136

In [ ]:
eth[['Close', 'retorno']].head()

Price             Close   retorno
Ticker          ETH-USD
Date
2026-04-01  2138.737061       NaN
2026-04-02  2056.852539 -0.038286
2026-04-03  2053.385254 -0.001686
2026-04-04  2065.351562  0.005828
2026-04-05  2108.995605  0.021132

In [ ]:
sol[['Close', 'retorno']].head()

Price           Close   retorno
Ticker        SOL-USD
Date
2026-04-01  81.195259       NaN
2026-04-02  78.951317 -0.027636
2026-04-03  80.368546  0.017951
2026-04-04  80.808380  0.005473
2026-04-05  81.854492  0.012946

In [ ]:
ada[['Close', 'retorno']].head()

Price          Close   retorno
Ticker       ADA-USD
Date
2026-04-01  0.248058       NaN
2026-04-02  0.239358 -0.035072
2026-04-03  0.246168  0.028451
2026-04-04  0.247949  0.007235
2026-04-05  0.250427  0.009994

In [ ]:
ltc[['Close', 'retorno']].head()

Price           Close   retorno
Ticker        LTC-USD
Date
2026-04-01  53.805855       NaN
2026-04-02  52.260174 -0.028727
2026-04-03  53.208050  0.018138
2026-04-04  53.574547  0.006888
2026-04-05  54.114513  0.010079